name: "Deploy MkDocs to GitHub Pages"
description: "Builds and deploys MkDocs site to a subdirectory on GitHub Pages using Poetry"

inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.11"
  github-token:
    description: "GitHub Token for deployment"
    required: true
  sha:
    description: "SHA of the commit"
    required: true
  ref_name:
    description: "Name of the branch"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Poetry
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Install Dependencies
      shell: bash
      run: poetry install --no-interaction --no-root

    - name: Ensure MkDocs & Material Theme are Installed
      shell: bash
      run: poetry add mkdocs mkdocs-material

    - name: Build MkDocs Site (to pages subdirectory)
      shell: bash
      run: poetry run mkdocs build --clean

    - name: Configure Git for gh-pages
      shell: bash
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Clone gh-pages branch
      shell: bash
      run: |
        git clone --depth=1 --branch gh-pages https://x-access-token:${{ inputs.github-token }}@github.com/${{ github.repository }} gh-pages

    - name: Copy Javadocs to gh-pages root
      shell: bash
      run: |
        cp -a ./site/. gh-pages/

    - name: Create .nojekyll in gh-pages
      shell: bash
      run: |
        touch gh-pages/.nojekyll

    - name: Deploy to GitHub Pages
      shell: bash
      run: |
        cd gh-pages
        git add .
        git commit -m "Deploy MkDocs from ${{ inputs.sha }} on branch ${{ inputs.ref_name }}"
        git push origin gh-pages