name: "Deploy MkDocs to GitHub Pages"
description: "Builds and deploys MkDocs site to a subdirectory on GitHub Pages using Poetry"

inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.11"
  github-token:
    description: "GitHub Token for deployment"
    required: true
  sha:
    description: "SHA of the commit"
    required: true
  ref_name:
    description: "Name of the branch"
    required: true
  branch:
    description: "Name of the branch to deploy to."
    required: false
    default: "pages"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Poetry
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Install Dependencies
      shell: bash
      run: poetry install --no-interaction --no-root

    - name: Ensure MkDocs & Material Theme are Installed
      shell: bash
      run: poetry add mkdocs mkdocs-material mkdocstrings-python mkdocs-markdownextradata-plugin markdown-grid-tables neoteroi-mkdocs mkdocs-glightbox

    - name: Build MkDocs Site (to pages subdirectory)
      shell: bash
      run: poetry run mkdocs build --clean

    - name: Configure Git for pages
      shell: bash
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Clone pages branch
      shell: bash
      run: |
        git clone --depth=1 --branch ${{ inputs.branch }} https://x-access-token:${{ inputs.github-token }}@github.com/${{ github.repository }} ${{ inputs.branch }}

    - name: Copy Javadocs to gh-pages root
      shell: bash
      run: |
        cp -a ./site/. ${{ inputs.branch }}/

    - name: Create .nojekyll in gh-pages
      shell: bash
      run: |
        touch ${{ inputs.branch }}/.nojekyll

    - name: Deploy to GitHub Pages
      shell: bash
      run: |
        cd ${{ inputs.branch }}
        if [[ -z $(git status --porcelain) ]]; then
          echo "No changes to deploy. Skipping deployment."
          exit 0
        fi
        git add .
        git commit -m "Deploy MkDocs from ${{ inputs.sha }} on branch ${{ inputs.ref_name }}"
        git push origin ${{ inputs.branch }}
