name: Publish Javadocs
description: 'Publish Javadocs to GitHub Pages'

inputs:
  sha:
    required: true
    description: 'The commit SHA'
  ref-name:
    required: true
    description: 'The branch name'
  java-version:
    required: true
    description: 'The Java version to use'
  distribution:
    required: true
    description: 'The Java distribution to use'
  github-token:
    required: true
    description: 'The GitHub token'
  branch:
    required: false
    description: 'The branch to deploy to'
    default: 'docs'

runs:
  using: "composite"

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK (Amazon Corretto)
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Generate Javadocs for all modules
      shell: bash
      run: |
        mvn clean package source:jar javadoc:jar -DskipTests -Dpmd.skip=true -Dcheckstyle.skip=true

    - name: Configure Git for pages
      shell: bash
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Clone pages branch
      shell: bash
      run: |
        git clone --depth=1 --branch ${{ inputs.branch }} https://x-access-token:${{ inputs.github-token }}@github.com/${{ github.repository }} ${{ inputs.branch }}

    - name: Copy Javadocs to pages root
      shell: bash
      run: |
        cp -a target/site/apidocs/. ${{ inputs.branch }}/

    - name: Create .nojekyll in pages
      shell: bash
      run: |
        touch ${{ inputs.branch }}/.nojekyll

    - name: Deploy to GitHub Pages
      shell: bash
      run: |
        cd ${{ inputs.branch }}
        git add .
        git commit -m "Deploy Javadocs from ${{ inputs.sha }} on branch ${{ inputs.ref-name }}"
        git push origin ${{ inputs.branch }}