name: Secure
description: "Robust, language-agnostic security scanning using CodeQL for static analysis and vulnerability detection."

inputs:
  languages:
    description: "Languages to analyze (e.g., 'javascript,python')."
    required: false
    default: "javascript,python"
  queries:
    description: "Optional additional CodeQL queries."
    required: false
    default: ""
  config-file:
    description: "Optional CodeQL config YAML content."
    required: false
    default: |
      paths-ignore:
        - '/usr/**'
        - '**/venv/**'
        - '**/.venv/**'
        - '**/site-packages/**'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create CodeQL config file
      shell: bash
      run: |
        echo "${{ inputs.config-file }}" > codeql-config.yml

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ inputs.languages }}
        queries: ${{ inputs.queries }}
        config-file: ./codeql-config.yml

    - name: Autobuild code
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Upload CodeQL results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: codeql-bundle/codeql.sarif