name: Secure
description: "Robust, language-agnostic security scanning using CodeQL for static analysis and vulnerability detection."

inputs:
  languages:
    description: "Comma-separated list of languages to analyze (e.g., 'javascript,python,cpp')."
    required: false
    default: "javascript,python,cpp"
  queries:
    description: "Optional additional CodeQL queries (comma-separated paths or repo references)."
    required: false
    default: ""
  config-file:
    description: "Optional CodeQL configuration file content to customize paths to include or ignore."
    required: false
    default: "parkermmr/compendium/jobs/security/secure/config.yml@v1"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ inputs.languages }}
        queries: ${{ inputs.queries }}
        config-file: ${{ inputs.config-file }}

    - name: Autobuild code
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
