name: Compile
description: 'Compile the project with Maven'

inputs:
  java-version:
    required: true
    description: 'The Java version to use'
  distribution:
    required: true
    description: 'The distribution of Java to use'

runs:
  using: "composite"

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK (Amazon Corretto)
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Build with Maven
      shell: bash
      id: build
      run: mvn clean compile -DskipTests