name: Java Pipeline

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: "17"
      distribution:
        required: false
        type: string
        default: "corretto"
      ref-name:
        required: false
        type: string
        default: "main"
      sha:
        required: false
        type: string
        default: "main"
    secrets:
      TOKEN:
        required: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/java/lint-checkstyle@v1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}

  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/java/maven/compile@v1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}

  Test:
    needs: ["Compile", "Lint"]
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/java/maven/test-junit@v1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
    
  Tag:
    needs: ["Test"]
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/release/deploy-tag@v1
        with:
          ref-name: ${{ inputs.ref-name }}
          sha: ${{ inputs.sha }}

  Document:
    needs: ["Test"]
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/java/maven/javadocs-publish@v1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          ref-name: ${{ inputs.ref-name }}
          sha: ${{ inputs.sha }}
          github-token: ${{ secrets.TOKEN }}
  