name: Python Linting and Testing with Docker Build

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
      repo:
        type: string
        required: true
      sha:
        type: string
        required: true
      ref-name:
        type: string
        required: true
      registry:
        type: string
        required: false
        default: "docker.io"
      config-file:
        required: false
        type: string
        default: "parkermmr/compendium/jobs/security/secure/config.yml@main"
    secrets:
      CODECOV_TOKEN:
        required: false
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/python/lint-flake8@v1
        with:
          python-version: ${{ inputs.python-version }}

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/python/poetry/pytest@v1
        with:
          python-version: ${{ inputs.python-version }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
  
  Secure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: parkermmr/compendium/jobs/security/secure@v1
        with:
          languages: "python"
          config-file: ${{ inputs.config-file }}

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/docker/build@v1
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repo: ${{ inputs.repo }}
          sha: ${{ inputs.sha }}
          ref-name: ${{ inputs.ref-name }}
          registry: ${{ inputs.registry }}
