name: Python Linting and Testing with Docker Build

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
    secrets:
      CODECOV_TOKEN:
        required: false
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/python/python-lint-flake8@v1
        with:
          python-version: ${{ inputs.python-version }}

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/python/python-poetry-pytest@v1
        with:
          python-version: ${{ inputs.python-version }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    steps:
      - uses: parkermmr/compendium/jobs/docker/build@v1
        with:
          image-name: "r3dsc0rp10n/test-image:latest"
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
