name: Python Tests with Poetry

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry (Ensure Virtualenvs are Created Inside Project)
        run: poetry config virtualenvs.in-project true

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Tests with Coverage
        run: |
          poetry run pytest --junitxml=reports/test-results.xml --cov=. --cov-report=xml:reports/coverage.xml --cov-report=html:reports/htmlcov --cov-report=term

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/test-results.xml
          retention-days: 7

      - name: Upload Coverage Report (XML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: reports/coverage.xml
          retention-days: 7

      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: reports/htmlcov/
          retention-days: 7
