name: Python Linting with Flake8

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry (Ensure Virtualenvs are Created Inside Project)
        run: poetry config virtualenvs.in-project true

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Install Linter & Formatters
        run: poetry add --dev flake8 flake8-html black isort

      - name: Create Reports Directory
        run: mkdir -p reports/flake8

      - name: Run Flake8 Linter (Generate Report)
        run: poetry run flake8 --exclude .venv --format=html --htmldir=reports/flake8

      - name: Run Black Formatter Check (Allow Failures)
        run: poetry run black --check --diff . || true

      - name: Run isort Import Sorting Check
        run: poetry run isort --check-only --diff .

      - name: Upload Linting Results (Flake8 HTML Report)
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: reports/flake8/
          retention-days: 7
